version: '3.6'
services:
  indexer-base:
    container_name: mainnet-indexer-base
    build:
      context: .
      dockerfile: ./apps/indexer-base/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: mainnet.indexer.env
  indexer-balance:
    container_name: mainnet-indexer-balance
    build:
      context: .
      dockerfile: ./apps/indexer-balance/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: mainnet.indexer.env
  indexer-events:
    container_name: mainnet-indexer-events
    build:
      context: .
      dockerfile: ./apps/indexer-events/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: mainnet.indexer.env

volumes:
  redis-data:
