name: nearblocks
services:
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    ports:
      - '127.0.0.1:3005:3000'
    environment:
      PORT: 3000
      NEXT_PUBLIC_NETWORK_ID: mainnet
      NEXT_PUBLIC_BOS_NETWORK: mainnet
      NEXT_PUBLIC_ACCOUNT_ID: nearblocksonbos.near
      NEXT_PUBLIC_OG_URL: https://meta.exploreblocks.io/api
      NEXT_PUBLIC_MAINNET_URL: https://nearblocks.io
      NEXT_PUBLIC_TESTNET_URL: https://testnet.nearblocks.io
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_SES_FROM_EMAIL: ${AWS_SES_FROM_EMAIL}
      AWS_SES_TO_EMAIL: ${AWS_SES_TO_EMAIL}
      NEXT_PUBLIC_GTM_ID: GTM-P285ZPV2
      NEXT_PUBLIC_USER_API_URL: https://api.exploreblocks.io/api/
      NEXT_PUBLIC_USER_DASHBOARD_URL: https://dash.nearblocks.io/
      NEXT_PUBLIC_API_URL: https://api.nearblocks.io/v1/
      API_URL: https://api.nearblocks.io/v1/
      API_ACCESS_KEY: ${API_ACCESS_KEY}
      NEXT_PUBLIC_TURNSTILE_SITE_KEY: ${NEXT_PUBLIC_TURNSTILE_SITE_KEY}
      TURNSTILE_SECRET_KEY: ${TURNSTILE_SECRET_KEY}
      NEXT_PUBLIC_SENTRY_DSN: ${NEXT_PUBLIC_SENTRY_DSN}
