#name: explorer-selector
services:
  testnet:
    image: ${REGISTRY:-explorer-selector}:${COMMIT_SHA:-latest}
    build:
      context: .
      dockerfile: ./apps/explorer-selector/Dockerfile
      args:
        BUILDPLATFORM: linux/arm64
        NEXT_PUBLIC_NETWORK_ID: testnet
        NEXT_PUBLIC_BOS_NETWORK: mainnet
        NEXT_PUBLIC_ACCOUNT_ID: mr8ce_is.near
    restart: always
    ports:
      - '127.0.0.1:3003:3000'
    environment:
      NEXT_PUBLIC_NETWORK_ID: testnet
      NEXT_PUBLIC_BOS_NETWORK: mainnet
      NEXT_PUBLIC_ACCOUNT_ID: mr8ce_is.near
