name: explorer-selector
services:
  testnet:
    build:
      context: .
      dockerfile: ./apps/explorer-selector/Dockerfile
    restart: always
    ports:
      - '127.0.0.1:3003:3000'
    environment:
      PORT: 3000
      NEXT_PUBLIC_NETWORK_ID: testnet
      NEXT_PUBLIC_BOS_NETWORK: mainnet
      NEXT_PUBLIC_ACCOUNT_ID: nearblocks.testnet
