version: '3.6'
services:
  indexer-base:
    container_name: testnet-indexer-base
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: indexer-base
        APT_PACKAGES: 'ca-certificates git curl iputils-ping'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-receipts:
    container_name: testnet-indexer-receipts
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: indexer-receipts
        NEON: true
        APT_PACKAGES: 'ca-certificates git curl iputils-ping'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-events:
    container_name: testnet-indexer-events
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: indexer-events
        NEON: true
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-multichain:
    container_name: testnet-indexer-multichain
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: indexer-multichain
        NODE_ARGS: '--max-old-space-size=1536'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-staking:
    container_name: testnet-indexer-staking
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: indexer-staking
        NODE_ARGS: '--max-old-space-size=2048'
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-ft-state:
    container_name: testnet-indexer-ft-state
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: indexer-ft-state
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env

volumes:
  redis-data:
