version: "3.6"
services:
  backend:
    container_name: testnet-backend
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: testnet.env
