version: '3.6'
services:
  indexer-base:
    container_name: testnet-indexer-base
    build:
      context: .
      dockerfile: ./apps/indexer-base/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-receipts:
    container_name: testnet-indexer-receipts
    build:
      context: .
      dockerfile: ./apps/indexer-receipts/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-balance:
    container_name: testnet-indexer-balance
    build:
      context: .
      dockerfile: ./apps/indexer-balance/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-events:
    container_name: testnet-indexer-events
    build:
      context: .
      dockerfile: ./apps/indexer-events/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-dex:
    container_name: testnet-indexer-dex
    build:
      context: .
      dockerfile: ./apps/indexer-dex/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-multichain:
    container_name: testnet-indexer-multichain
    build:
      context: .
      dockerfile: ./apps/indexer-multichain/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-staking:
    container_name: testnet-indexer-staking
    build:
      context: .
      dockerfile: ./apps/indexer-staking/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  indexer-ft-state:
    container_name: testnet-indexer-ft-state
    build:
      context: .
      dockerfile: ./apps/indexer-ft-state/Dockerfile
    restart: always
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env
  ft-finder:
    container_name: testnet-ft-finder
    build:
      context: .
      dockerfile: ./apps/ft-finder/Dockerfile
    restart: 'no'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: testnet.indexer.env

volumes:
  redis-data:
