name: nearblocks
services:
  app:
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    restart: always
    ports:
      - '127.0.0.1:3006:3000'
    environment:
      PORT: 3000
      NEXT_PUBLIC_NETWORK_ID: testnet
      NEXT_PUBLIC_BOS_NETWORK: testnet
      NEXT_PUBLIC_ACCOUNT_ID: nearblocks.testnet
      NEXT_PUBLIC_OG_URL: https://meta.nearblocks.io/api
      NEXT_PUBLIC_MAINNET_URL: https://nearblocks.io
      NEXT_PUBLIC_TESTNET_URL: https://testnet.nearblocks.io
      BREVO_URL: https://api.brevo.com/v3/smtp/email
      BREVO_API_KEY: ${BREVO_API_KEY}
      BREVO_TO_EMAIL: ${BREVO_TO_EMAIL}
      NEXT_PUBLIC_GTM_ID: GTM-P285ZPV2
