import { sql } from '#sql/index';

export const blockRange = sql('queries/accounts/blockRange.sql');

export default {
  account: sql('queries/accounts/account.sql'),
  assets: {
    ftCount: sql('queries/accounts/assets/ftCount.sql'),
    fts: sql('queries/accounts/assets/fts.sql'),
    mtFtCount: sql('queries/accounts/assets/mtFtCount.sql'),
    mtFts: sql('queries/accounts/assets/mtFts.sql'),
    mtNftCount: sql('queries/accounts/assets/mtNftCount.sql'),
    mtNfts: sql('queries/accounts/assets/mtNfts.sql'),
    nftCount: sql('queries/accounts/assets/nftCount.sql'),
    nfts: sql('queries/accounts/assets/nfts.sql'),
  },
  balance: sql('queries/accounts/balance.sql'),
  balanceHistory: sql('queries/accounts/balanceHistory.sql'),
  contracts: {
    action: sql('queries/accounts/contracts/action.sql'),
    contract: sql('queries/accounts/contracts/contract.sql'),
    deployments: sql('queries/accounts/contracts/deployments.sql'),
    deploymentTxn: sql('queries/accounts/contracts/deploymentTxn.sql'),
  },
  fts: {
    count: sql('queries/accounts/fts/count.sql'),
    countCagg: sql('queries/accounts/fts/countCagg.sql'),
    countCaggContract: sql('queries/accounts/fts/countCaggContract.sql'),
    export: sql('queries/accounts/fts/export.sql'),
    exportTxn: sql('queries/accounts/fts/exportTxn.sql'),
    txn: sql('queries/accounts/fts/txn.sql'),
    txns: sql('queries/accounts/fts/txns.sql'),
  },
  keys: {
    count: sql('queries/accounts/keys/count.sql'),
    export: sql('queries/accounts/keys/export.sql'),
    keys: sql('queries/accounts/keys/keys.sql'),
  },
  mts: {
    contractCountCagg: sql('queries/accounts/mts/contractCountCagg.sql'),
    count: sql('queries/accounts/mts/count.sql'),
    countCagg: sql('queries/accounts/mts/countCagg.sql'),
    export: sql('queries/accounts/mts/export.sql'),
    exportTxn: sql('queries/accounts/mts/exportTxn.sql'),
    txn: sql('queries/accounts/mts/txn.sql'),
    txns: sql('queries/accounts/mts/txns.sql'),
  },
  nfts: {
    count: sql('queries/accounts/nfts/count.sql'),
    countCagg: sql('queries/accounts/nfts/countCagg.sql'),
    export: sql('queries/accounts/nfts/export.sql'),
    exportTxn: sql('queries/accounts/nfts/exportTxn.sql'),
    txn: sql('queries/accounts/nfts/txn.sql'),
    txns: sql('queries/accounts/nfts/txns.sql'),
  },
  receipts: {
    count: sql('queries/accounts/receipts/count.sql'),
    countCagg: sql('queries/accounts/receipts/countCagg.sql'),
    countUnion: sql('queries/accounts/receipts/countUnion.sql'),
    cte: sql('queries/accounts/receipts/cte.sql'),
    cteUnion: sql('queries/accounts/receipts/cteUnion.sql'),
    exportCte: sql('queries/accounts/receipts/exportCte.sql'),
    receipts: sql('queries/accounts/receipts/receipts.sql'),
  },
  staking: {
    count: sql('queries/accounts/staking/count.sql'),
    export: sql('queries/accounts/staking/export.sql'),
    exportTxn: sql('queries/accounts/staking/exportTxn.sql'),
    txn: sql('queries/accounts/staking/txn.sql'),
    txns: sql('queries/accounts/staking/txns.sql'),
  },
  stats: {
    balance: sql('queries/accounts/stats/balance.sql'),
    fts: sql('queries/accounts/stats/fts.sql'),
    mts: sql('queries/accounts/stats/mts.sql'),
    near: sql('queries/accounts/stats/near.sql'),
    nfts: sql('queries/accounts/stats/nfts.sql'),
    overview: sql('queries/accounts/stats/overview.sql'),
    txns: sql('queries/accounts/stats/txns.sql'),
  },
  txns: {
    count: sql('queries/accounts/txns/count.sql'),
    countCagg: sql('queries/accounts/txns/countCagg.sql'),
    countUnion: sql('queries/accounts/txns/countUnion.sql'),
    cte: sql('queries/accounts/txns/cte.sql'),
    cteUnion: sql('queries/accounts/txns/cteUnion.sql'),
    exportCte: sql('queries/accounts/txns/exportCte.sql'),
    txns: sql('queries/accounts/txns/txns.sql'),
  },
};
