{
 "title": "NearBlocks",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "block_height_latest", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(block_processing_ms_bucket[10])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Upload Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(s3_upload_ms_bucket[5s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Source",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "data_source_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(block_insertion_ms_bucket[10])))",
     "legendFormat": "Block"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(chunks_insertion_ms_bucket[10])))",
     "legendFormat": "Chunks"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(accounts_insertion_ms_bucket[10])))",
     "legendFormat": "Accounts"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(keys_insertion_ms_bucket[10])))",
     "legendFormat": "Access Keys"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(transactions_insertion_ms_bucket[10])))",
     "legendFormat": "Txns"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(outcomes_insertion_ms_bucket[10])))",
     "legendFormat": "Outcomes"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(receipts_insertion_ms_bucket[10])))",
     "legendFormat": "Receipts"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(s3_upload_ms_bucket[10])))",
     "legendFormat": "S3"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Block Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(block_processing_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "S3 Upload Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(s3_upload_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Cache Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(cache_processing_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Receipts Insertion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(receipts_insertion_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Outcomes Insertion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(outcomes_insertion_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Txns Insertion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(transactions_insertion_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Account Insertion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(accounts_insertion_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Access Keys Insertion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(keys_insertion_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Chunks Insertion Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(chunks_insertion_ms_bucket[10])))",
     "legendFormat": "Time"
    }
   ]
  }
 ]
}