ALTER TABLE ft_meta
ALTER price TYPE NUMERIC(32, 12),
ADD COLUMN IF NOT EXISTS volume_24h NUMERIC(36, 8),
ADD COLUMN IF NOT EXISTS change_24h NUMERIC(12, 4);

ALTER TABLE mt_token_meta
ALTER copies TYPE INTEGER,
ALTER extra TYPE TEXT;
