CREATE TABLE daily_stats (
  date BIGINT NOT NULL,
  near_price NUMERIC(28, 8),
  near_btc_price NUMERIC(28, 8),
  market_cap NUMERIC(28, 8),
  total_supply NUMERIC(45, 0),
  circulating_supply NUMERIC(45, 0),
  blocks INTEGER,
  chunks INTEGER,
  shards SMALLINT,
  gas_fee NUMERIC(45, 8),
  gas_used NUMERIC(45, 8),
  receipts BIGINT,
  txns INTEGER,
  meta_txns INTEGER,
  txn_volume NUMERIC(45, 8),
  txn_volume_usd NUMERIC(28, 8),
  txn_fee NUMERIC(45, 8),
  txn_fee_usd NUMERIC(28, 8),
  new_accounts INTEGER,
  new_contracts INTEGER,
  active_accounts INTEGER,
  active_meta_accounts INTEGER,
  active_meta_relayers INTEGER,
  active_contracts INTEGER,
  PRIMARY KEY (date)
);

CREATE TABLE nodes (
  node_id TEXT NOT NULL,
  ip_address TEXT NOT NULL,
  moniker TEXT,
  account_id TEXT,
  last_seen TIMESTAMPTZ,
  last_height TEXT,
  agent_name TEXT,
  agent_version TEXT,
  agent_build TEXT,
  peer_count TEXT,
  is_validator BOOLEAN,
  last_hash TEXT,
  signature TEXT,
  status TEXT,
  latitude TEXT,
  longitude TEXT,
  city TEXT,
  bandwidth_download NUMERIC,
  bandwidth_upload NUMERIC,
  cpu_usage NUMERIC,
  memory_usage TEXT,
  boot_time_seconds TIMESTAMPTZ,
  block_production_tracking_delay NUMERIC,
  min_block_production_delay NUMERIC,
  max_block_production_delay NUMERIC,
  max_block_wait_delay NUMERIC,
  PRIMARY KEY (node_id)
);

CREATE TABLE stats (
  total_txns BIGINT,
  nodes_online INTEGER,
  tps INTEGER,
  total_supply NUMERIC(45, 0),
  circulating_supply NUMERIC(45, 0),
  avg_block_time NUMERIC(28, 8),
  near_price NUMERIC(28, 8),
  near_btc_price NUMERIC(28, 8),
  change_24h NUMERIC(12, 4),
  market_cap NUMERIC(28, 8),
  volume_24h NUMERIC(28, 8),
  gas_price NUMERIC(20, 0)
);

CREATE TABLE validator_data (
  latest_block JSONB NULL,
  genesis_config JSONB NULL,
  protocol_config JSONB NULL,
  pool_ids JSONB NULL,
  validators_promise JSONB NULL,
  stake_proposals JSONB NULL,
  staking_pool_infos JSONB NULL,
  validator_lists JSONB NULL,
  mapped_validators JSONB NULL,
  current_validators JSONB NULL,
  epoch_stats_check JSONB NULL,
  epoch_start_block JSONB NULL,
  staking_pool_metadata JSONB NULL,
  validator_telemetry JSONB NULL
);
