[package]
name = "nb-lockup"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.51"
near-jsonrpc-client = "0.6.0"
near-indexer-primitives = "0.17.0"
near-jsonrpc-primitives = "0.17.0"
near-sdk = { git = "https://github.com/near/near-sdk-rs", rev="03487c184d37b0382dd9bd41c57466acad58fc1f" }
once_cell = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1.13"
uint = { version = "0.8.3", default-features = false }

[dependencies.neon]
version = "0.10"
default-features = false
features = ["channel-api", "napi-6", "promise-api"]
