name: Auto Comment
on:
  issues:
    types: [opened]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            :warning: **REMINDER**
            • NearBlocks does not process transactions and are therefore unable to revert, refund, expedite, cancel or replace them
            • NEVER share your private keys or wallet details
            • NEVER click on external links or download software from comments
            Thank you for raising an issue. We will investigate and respond as soon as possible.
