name: Build Docker Images
on:
  push:
    branches: ['main']
jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        include:
          - service: api
            file: Dockerfile
            args: |
              APP=api
          - service: frontend
            file: apps/frontend/Dockerfile
            args: ''
          - service: backend
            file: Dockerfile
            args: |
              APP=backend
              APT_PACKAGES=ca-certificates libssl-dev
          - service: indexer-base
            file: Dockerfile
            args: |
              APP=indexer-base
              APT_PACKAGES=ca-certificates git curl iputils-ping
          - service: indexer-balance
            file: Dockerfile
            args: |
              APP=indexer-balance
          - service: indexer-events
            file: Dockerfile
            args: |
              APP=indexer-events
              NEON=true
          - service: indexer-multichain
            file: Dockerfile
            args: |
              APP=indexer-multichain
              NODE_ARGS=--max-old-space-size=1536
          - service: indexer-signature
            file: Dockerfile
            args: |
              APP=indexer-signature
              NEON=true
              NODE_ARGS=--max-old-space-size=1536
          - service: indexer-staking
            file: Dockerfile
            args: |
              APP=indexer-staking
              NODE_ARGS=--max-old-space-size=2048
          - service: indexer-receipts
            file: Dockerfile
            args: |
              APP=indexer-receipts
              NEON=true
              APT_PACKAGES=ca-certificates git curl iputils-ping
          - service: indexer-accounts
            file: Dockerfile
            args: |
              APP=indexer-accounts
              NEON=true
              NODE_ARGS=--max-old-space-size=1536
              APT_PACKAGES=ca-certificates git curl iputils-ping xz-utils
          - service: indexer-contract
            file: Dockerfile
            args: |
              APP=indexer-contract
              NODE_ARGS=--max-old-space-size=6000
          - service: explorer-selector
            file: apps/explorer-selector/Dockerfile
            args: ''
          - service: aggregates
            file: Dockerfile
            args: |
              APP=aggregates
          - service: block-proxy
            file: Dockerfile
            args: |
              APP=block-proxy
              APT_PACKAGES=ca-certificates wget
          - service: indexer-intents
            file: Dockerfile
            args: |
              APP=indexer-intents
          - service: indexer-tvl
            file: Dockerfile
            args: |
              APP=indexer-tvl
              NODE_ARGS=--max-old-space-size=1536
          - service: indexer-ft-state
            file: Dockerfile
            args: |
              APP=indexer-ft-state
      fail-fast: false
    steps:
      - uses: actions/checkout@v7
      - uses: docker/setup-qemu-action@v4
        with:
          platforms: linux/amd64
      - uses: docker/setup-buildx-action@v4
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Determine image tag
        run: |
          if [ "${{ matrix.service }}" = "api" ] || [ "${{ matrix.service }}" = "indexer-base" ] || [ "${{ matrix.service }}" = "indexer-receipts" ] || [ "${{ matrix.service }}" = "indexer-balance" ] || [ "${{ matrix.service }}" = "indexer-events" ] || [ "${{ matrix.service }}" = "backend" ] || [ "${{ matrix.service }}" = "aggregates" ]; then
            echo "TAG=:v2" >> $GITHUB_ENV
          else
            echo "TAG=:latest" >> $GITHUB_ENV
          fi
      - name: Get current image digest
        run: |
          CURRENT_DIGEST=$(docker manifest inspect ghcr.io/nearblocks/${{ matrix.service }}${{ env.TAG }} | jq -r '.config.digest' || echo "")
          echo "CURRENT_DIGEST=$CURRENT_DIGEST" >> $GITHUB_ENV
      - uses: docker/build-push-action@v7
        id: build
        with:
          context: .
          file: ${{ matrix.file }}
          platforms: linux/amd64
          push: true
          provenance: false
          tags: |
            ghcr.io/nearblocks/${{ matrix.service }}${{ env.TAG }}
            ghcr.io/nearblocks/${{ matrix.service }}:${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/nearblocks/${{ matrix.service }}${{ env.TAG }}
          cache-to: type=inline
          build-args: |
            ${{ matrix.args }}
            GITHUB_SHA=${{ github.sha }}
            NEXT_SERVER_ACTIONS_ENCRYPTION_KEY=${{ secrets.NEXT_SERVER_ACTIONS_ENCRYPTION_KEY }}

      - name: Get new image digest
        run: |
          NEW_DIGEST=$(docker manifest inspect ghcr.io/nearblocks/${{ matrix.service }}${{ env.TAG }} | jq -r '.config.digest')
          echo "NEW_DIGEST=$NEW_DIGEST" >> $GITHUB_ENV

#      - name: Deploy testnet
#        if: |
#          env.CURRENT_DIGEST != env.NEW_DIGEST &&
#          matrix.service != 'indexer-dex' &&
#          matrix.service != 'indexer-s3' &&
#          matrix.service != 'explorer-selector'
#        run: |
#          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > kubeconfig
#          export KUBECONFIG=$(pwd)/kubeconfig
#
#          kubectl set -n nearblocks-testnet image deployment/testnet-${{ matrix.service }} ${{ matrix.service }}=ghcr.io/nearblocks/${{ matrix.service }}:${{ github.sha }}
#          kubectl rollout -n nearblocks-testnet status deployment/testnet-${{ matrix.service }} --timeout=600s
