ALTER TYPE action_kind
ADD VALUE 'DEPLOY_GLOBAL_CONTRACT';

ALTER TYPE action_kind
ADD VALUE 'DEPLOY_GLOBAL_CONTRACT_BY_ACCOUNT_ID';

ALTER TYPE action_kind
ADD VALUE 'USE_GLOBAL_CONTRACT';

ALTER TYPE action_kind
ADD VALUE 'USE_GLOBAL_CONTRACT_BY_ACCOUNT_ID';
