[package]
name = "nb-json"
version = "0.1.0"
license = "ISC"
edition = "2018"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neon-serde3 = "0.10.0"
serde_json = "1.0.85"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
